(function(){
"use strict";
var body=document.body,moduleId=body.dataset.module||"00",key="owos:aia001:"+moduleId+":master:v1",saved={};
try{saved=JSON.parse(localStorage.getItem(key)||"{}");}catch(error){}
function persist(){localStorage.setItem(key,JSON.stringify(saved));updateCompletion();}
function mark(id){saved[id]=true;persist();}
function updateCompletion(){var required=[].slice.call(document.querySelectorAll("[data-required]")),done=required.filter(function(el){return el.classList.contains("done")||saved[el.dataset.required];}).length,button=document.querySelector("[data-complete]"),status=document.querySelector("[data-completion-status]");if(button)button.disabled=done<required.length;if(status)status.textContent=done+" of "+required.length+" required learning activities complete.";required.forEach(function(el){if(saved[el.dataset.required])el.classList.add("done");});}
document.querySelectorAll("[data-quiz]").forEach(function(quiz){var id=quiz.dataset.quiz,mode=quiz.dataset.mode||"single",feedback=quiz.querySelector(".feedback");quiz.addEventListener("click",function(event){var choice=event.target.closest(".choice");if(!choice)return;if(mode==="multi")choice.classList.toggle("selected");else{quiz.querySelectorAll(".choice").forEach(function(item){item.classList.remove("selected");});choice.classList.add("selected");}});var check=quiz.querySelector("[data-check]");if(check)check.onclick=function(){var options=[].slice.call(quiz.querySelectorAll(".choice")),ok=true;options.forEach(function(option){var want=option.dataset.correct==="1",got=option.classList.contains("selected");option.classList.remove("correct","wrong");if(want)option.classList.add("correct");if(got&&!want)option.classList.add("wrong");if(want!==got)ok=false;});feedback.classList.add("show");feedback.textContent=ok?quiz.dataset.pass:"Review the highlighted choices and try again. "+(quiz.dataset.retry||"Use the operating rule explained above.");if(ok){quiz.classList.add("done");mark(id);}};});
document.querySelectorAll("[data-match]").forEach(function(quiz){var id=quiz.dataset.match,feedback=quiz.querySelector(".feedback");quiz.querySelector("[data-check]").onclick=function(){var fields=[].slice.call(quiz.querySelectorAll("select[data-answer]")),correct=fields.filter(function(field){var ok=field.value===field.dataset.answer;field.style.borderColor=ok?"#0e8a64":"#c84444";return ok;}).length;feedback.classList.add("show");feedback.textContent=correct===fields.length?quiz.dataset.pass:correct+" of "+fields.length+" matches are correct. Read each plain-English definition and try again.";if(correct===fields.length){quiz.classList.add("done");mark(id);}};});
document.querySelectorAll("[data-stepper]").forEach(function(root){var id=root.dataset.stepper,steps=[].slice.call(root.querySelectorAll(".step")),buttons=[].slice.call(root.querySelectorAll(".stepnav button")),index=0,timer=null,meter=root.querySelector(".meter i");function paint(i){index=Math.max(0,Math.min(steps.length-1,i));steps.forEach(function(step,j){step.classList.toggle("active",j===index);});buttons.forEach(function(button,j){button.classList.toggle("active",j===index);});meter.style.width=((index+1)/steps.length*100)+"%";if(index===steps.length-1){root.classList.add("done");mark(id);}}function stop(){if(timer){clearInterval(timer);timer=null;}}buttons.forEach(function(button,i){button.onclick=function(){stop();paint(i);};});var back=root.querySelector("[data-back]"),next=root.querySelector("[data-next]"),play=root.querySelector("[data-play]"),pause=root.querySelector("[data-pause]"),reset=root.querySelector("[data-reset]");if(back)back.onclick=function(){stop();paint(index-1);};if(next)next.onclick=function(){stop();paint(index+1);};if(play)play.onclick=function(){stop();if(index===steps.length-1)paint(0);timer=setInterval(function(){if(index===steps.length-1){stop();return;}paint(index+1);},1800);};if(pause)pause.onclick=stop;if(reset)reset.onclick=function(){stop();paint(0);};paint(0);});
document.querySelectorAll("[data-lab]").forEach(function(lab){var id=lab.dataset.lab,result=lab.querySelector(".labresult");lab.querySelectorAll("[data-lab-option]").forEach(function(button){button.onclick=function(){lab.querySelectorAll("[data-lab-option]").forEach(function(item){item.classList.toggle("on",item===button);});result.innerHTML="<h3>"+button.dataset.title+"</h3><p>"+button.dataset.result+"</p>";if(button.dataset.complete==="1"){lab.classList.add("done");mark(id);}};});});
document.querySelectorAll("form[data-artifact]").forEach(function(form){var id=form.dataset.artifact,preview=form.closest(".artifact").querySelector("pre"),fields=[].slice.call(form.querySelectorAll("input,textarea,select"));function text(){return fields.map(function(field){return (field.dataset.label||field.previousSibling.textContent||field.name).trim().toUpperCase()+"\n"+(field.value.trim()||"[Complete]");}).join("\n\n");}function render(){preview.textContent=text();}fields.forEach(function(field){field.addEventListener("input",render);});form.onsubmit=function(event){event.preventDefault();var valid=fields.every(function(field){return field.value.trim().length>2;});var feedback=form.querySelector(".feedback");feedback.classList.add("show");feedback.textContent=valid?"Saved in this browser as a professional draft. Review it with the named utility owner.":"Complete every field with a specific, testable statement.";if(valid){saved[id+"-data"]=fields.map(function(field){return field.value;});form.closest(".artifact").classList.add("done");mark(id);}};if(saved[id+"-data"])fields.forEach(function(field,i){field.value=saved[id+"-data"][i]||"";});render();});
document.querySelectorAll("[data-open-graph]").forEach(function(button){button.onclick=function(){var drawer=document.querySelector(".drawer"),scrim=document.querySelector(".scrim");drawer.classList.add("open");scrim.classList.add("open");drawer.setAttribute("aria-hidden","false");drawer.querySelector("[data-close-graph]").focus();};});function closeGraph(){var drawer=document.querySelector(".drawer"),scrim=document.querySelector(".scrim");if(drawer){drawer.classList.remove("open");scrim.classList.remove("open");drawer.setAttribute("aria-hidden","true");}}var close=document.querySelector("[data-close-graph]"),scrim=document.querySelector(".scrim");if(close)close.onclick=closeGraph;if(scrim)scrim.onclick=closeGraph;document.addEventListener("keydown",function(event){if(event.key==="Escape")closeGraph();});
var complete=document.querySelector("[data-complete]");if(complete)complete.onclick=function(){this.textContent="Module complete";saved.completed=true;persist();};
window.addEventListener("scroll",function(){var root=document.documentElement,max=root.scrollHeight-root.clientHeight,bar=document.querySelector(".reading");if(bar)bar.style.width=(max?root.scrollTop/max*100:0)+"%";});updateCompletion();
})();
